name: cucumber-playwright-fw
on: push
env: 
  ENV: dev
jobs:
  test:
   timeout-minutes: 60
   name: Run UI Tests
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-node@v3
       with:
         node-version: 18
     - name: Install Dependencies
       run: npm ci
     - name: Install Playwright Browsers
       run: npx playwright install --with-deps  
     - name: Run Dev Tests
       run: npm run dev
     - name: Generate Reports
       if: always()
       run: npm run generate-report
     - name: Archive Test Results
       if: always()
       uses: actions/upload-artifact@v3
       with:
         name: cucumber-results
         path: test-results/reports/cucumber-report.html 
