name: cucumber-playwright-fw
on: push

jobs:
  job1:
   name: Run UI Tests
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/Checkout@v4
     - name: Install dependencies
       run: npm install
     - name: Install playwright dependencies
       run: npx playwright install --with-deps  
     - name: Run Dev Tests
       run: npx cross-env ENV=dev cucumber-js  